spring.application.name=discovery_service
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
server.port=8761
eureka.dashboard.enabled=true
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO
spring.security.user.name=admin
spring.security.user.password=admin
