spring.application.name=filieres
spring.config.import=optional:configserver:http://localhost:8888spring.datasource.username=root
spring.datasource.password=tahiry4534
spring.cloud.config.override-none=true
