spring.application.name=api_gateway

server.port=8090

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=president
spring.cloud.gateway.routes[0].uri=lb://PRESIDENT
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/mots/**

spring.cloud.gateway.routes[1].id=utilisateur
spring.cloud.gateway.routes[1].uri=lb://UTILISATEUR
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[2].id=actualite
spring.cloud.gateway.routes[2].uri=lb://ACTUALITE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/actualites/**

spring.cloud.gateway.routes[3].id=emploiDuTemps
spring.cloud.gateway.routes[3].uri=lb://EMPLOIDUTEMPS
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/emploiDuTemps/**

spring.cloud.gateway.routes[4].id=demo
spring.cloud.gateway.routes[4].uri=lb://DEMO
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/encadrements/**

spring.cloud.gateway.routes[5].id=demo
spring.cloud.gateway.routes[5].uri=lb://DEMO
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/encadreurs/**

spring.cloud.gateway.routes[6].id=demo
spring.cloud.gateway.routes[6].uri=lb://DEMO
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/enseignants/**

spring.cloud.gateway.routes[7].id=demo
spring.cloud.gateway.routes[7].uri=lb://DEMO
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/etudiants/**

spring.cloud.gateway.routes[8].id=historique
spring.cloud.gateway.routes[8].uri=lb://HISTORIQUE
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/histoires/**

spring.cloud.gateway.routes[9].id=matiere
spring.cloud.gateway.routes[9].uri=lb://MATIERE
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/matieres/**

spring.cloud.gateway.routes[10].id=note
spring.cloud.gateway.routes[10].uri=lb://NOTE
spring.cloud.gateway.routes[10].predicates[0]=Path=/api/notes/**

spring.cloud.gateway.routes[11].id=organigramme
spring.cloud.gateway.routes[11].uri=lb://ORGANIGRAMME
spring.cloud.gateway.routes[11].predicates[0]=Path=/api/organigrammes/**

spring.cloud.gateway.routes[12].id=presence
spring.cloud.gateway.routes[12].uri=lb://PRESENCE
spring.cloud.gateway.routes[12].predicates[0]=Path=/api/presences/**

spring.cloud.gateway.routes[13].id=slide
spring.cloud.gateway.routes[13].uri=lb://SLIDE
spring.cloud.gateway.routes[13].predicates[0]=Path=/api/slides/**


